version: '3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: linkprof/foodgram-backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: linkprof/foodgram-frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  gateway:
    image: linkprof/foodgram-nginx
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs
      - redoc:/usr/share/nginx/api/docs/
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend