version: '3.3'

volumes:
  pg_data:
  static:
  media:
  backend_static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: linkprof/foodgram-backend
    env_file: .env
    depends_on:
      - db
      - frontend
    volumes:
      - backend_static:/app/static
      - media:/app/media/
      - ./docs:/usr/share/nginx/html/docs

  frontend:
    env_file: .env
    image: linkprof/foodgram-frontend
    volumes:
      - static:/app/result_build/build/

  nginx:
    image: linkprof/foodgram-nginx
    depends_on:
      - backend
    ports:
      - "9000:80"
    volumes:
      - static:/usr/share/nginx/html/
      - backend_static:/app/static/
      - media:/app/media/
      - ./docs:/usr/share/nginx/html/docs