version: '3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: linkprof/foodgram-backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: linkprof/foodgram-frontend
    volumes:
      - static_frontend:/app/result_build/
  gateway:
    image: linkprof/foodgram-nginx
    env_file: .env
    volumes:
      - static:/static
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_frontend:/static_frontend/
    ports:
      - 6000:80
    depends_on:
      - backend