version: '3'

volumes:
  foodgram_pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
  backend:
    image: linkprof/backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media
  frontend:
    image: linkprof/frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: linkprof/nginx
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/static/
      - media_volume:/app/media
    ports:
      - 8000:80