version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: linkprof/foodgram-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static_django/
      - media:/app/media/
      - ./docs:/usr/share/nginx/html/docs

  frontend:
    env_file: .env
    image: linkprof/foodgram-frontend
    command: cp -r /app/build/ . /static_frontend/
    volumes:
      - static_frontend:/app/result_build/

  nginx:
    image: linkprof/foodgram-nginx
    depends_on:
      - backend
    ports:
      - "9000:80"
    volumes:
      - static:/static_django/
      - media:/app/media/
      - ./docs:/usr/share/nginx/html/api/docs
      - static_frontend:/static_frontend/