version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db


  frontend:
    build: ./frontend
    volumes:
      - static_frontend:/app/result_build/
    depends_on:
      - backend
      - db
  
  nginx:
    image: nginx:1.22.1
    ports:
      - '8090:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_frontend:/static_frontend/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static_django/
      - media:/app/media
    depends_on:
      - frontend
