version: '3.3'

volumes:
  foodgram_pg_data:
  static:
  media:

services:


  foodgram_db:
    image: postgres:13.0-alpine
    env_file:
      - .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data/


  backend:
      build:
        context: ../backend
        dockerfile: Dockerfile
      env_file:
        - .env
      restart: always
      volumes:
        - static:/static/
        - media:/app/media/
      depends_on:
        - foodgram_db


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
      depends_on:
        - backend
  
  
  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media